const ROLES = {
  superAdmin: 1,
  admin: 2,
  standard: 3,
  limited: 4,
};

const CONTACT_FILTERS = {
  marital_status: 'exact',
  political_exposure: 'exact',
  residence_status: 'exact',
  profession: 'exact',
  risk_profile: 'exact',
  contact_owner: 'exact',
  contact_status: 'exact',
  industry: 'exact',
  contact_source: 'exact',
  anniversary_date: 'range_date',
  gross_annual_income: 'range_integer',
};

const IS_GROUP_HEAD = [
  { label: 'Yes', value: true },
  { label: 'No', value: false },
];

const RELATIONSHIP_GROUP_HEAD = [
  { label: 'Self', value: 'Self' },
  { label: 'Mother', value: 'Mother' },
  { label: 'Father', value: 'Father' },
  { label: 'Daughter', value: 'Daughter' },
  { label: 'Son', value: 'Son' },
  { label: 'Sister', value: 'Sister' },
  { label: 'Brother', value: 'Brother' },
  { label: 'Aunt', value: 'Aunt' },
  { label: 'Uncle', value: 'Uncle' },
  { label: 'Niece', value: 'Niece' },
  { label: 'Nephew', value: 'Nephew' },
  { label: 'Cousin (female)', value: 'Cousin (female)' },
  { label: 'Cousin (male)', value: 'Cousin (male)' },
  { label: 'Grandmother', value: 'Grandmother' },
  { label: 'Grandfather', value: 'Grandfather' },
  { label: 'Granddaughter', value: 'Granddaughter' },
  { label: 'Grandson', value: 'Grandson' },
  { label: 'Stepsister', value: 'Stepsister' },
  { label: 'Stepbrother', value: 'Stepbrother' },
  { label: 'Stepmother', value: 'Stepmother' },
  { label: 'Stepfather', value: 'Stepfather' },
  { label: 'Stepdaughter', value: 'Stepdaughter' },
  { label: 'Stepson', value: 'Stepson' },
  { label: 'Sister-in-law', value: 'Sister-in-law' },
  { label: 'Brother-in-law', value: 'Brother-in-law' },
  { label: 'Mother-in-law', value: 'Mother-in-law' },
  { label: 'Father-in-law', value: 'Father-in-law' },
  { label: 'Daughter-in-law', value: 'Daughter-in-law' },
  { label: 'Son-in-law', value: 'Son-in-law' },
  { label: 'Family Friend', value: 'Family Friend' },
  { label: 'Pet', value: 'Pet' },
];

const RELATIONSHIP_MATRIX = {
  Self: {
    Mother: 'Mother',
    Father: 'Father',
    Daughter: 'Daughter',
    Son: 'Son',
    Sister: 'Sister',
    Brother: 'Brother',
    Aunt: 'Aunt',
    Uncle: 'Uncle',
    Niece: 'Niece',
    Nephew: 'Nephew',
    'Cousin (female)': 'Cousin (female)',
    'Cousin (male)': 'Cousin (male)',
    Grandmother: 'Grandmother',
    Grandfather: 'Grandfather',
    Granddaughter: 'Granddaughter',
    Grandson: 'Grandson',
    Stepsister: 'Stepsister',
    Stepbrother: 'Stepbrother',
    Stepmother: 'Stepmother',
    Stepfather: 'Stepfather',
    Stepdaughter: 'Stepdaughter',
    Stepson: 'Stepson',
    'Sister-in-law': 'Sister-in-law',
    'Brother-in-law': 'Brother-in-law',
    'Mother-in-law': 'Mother-in-law',
    'Father-in-law': 'Father-in-law',
    'Daughter-in-law': 'Daughter-in-law',
    'Son-in-law': 'Son-in-law',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Mother: {
    Self: 'Child',
    Father: 'Partner/Spouse',
    Daughter: 'Sibling',
    Son: 'Sibling',
    Sister: 'Aunt/Uncle',
    Brother: 'Aunt/Uncle',
    Aunt: 'Great Aunt/Uncle',
    Uncle: 'Great Aunt/Uncle',
    Niece: 'Cousin',
    Nephew: 'Cousin',
    'Cousin (female)': 'Second Cousin',
    'Cousin (male)': 'Second Cousin',
    Grandmother: 'Great Grandparent',
    Grandfather: 'Great Grandparent',
    Granddaughter: 'Grandchild',
    Grandson: 'Grandchild',
    Stepsister: 'Step Aunt/Uncle',
    Stepbrother: 'Step Aunt/Uncle',
    Stepmother: 'Step Parent',
    Stepfather: 'Step Parent',
    Stepdaughter: 'Step Sibling',
    Stepson: 'Step Sibling',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Father: {
    Self: 'Child',
    Mother: 'Partner/Spouse',
    Daughter: 'Sibling',
    Son: 'Sibling',
    Sister: 'Aunt/Uncle',
    Brother: 'Aunt/Uncle',
    Aunt: 'Great Aunt/Uncle',
    Uncle: 'Great Aunt/Uncle',
    Niece: 'Cousin',
    Nephew: 'Cousin',
    'Cousin (female)': 'Second Cousin',
    'Cousin (male)': 'Second Cousin',
    Grandmother: 'Great Grandparent',
    Grandfather: 'Great Grandparent',
    Granddaughter: 'Grandchild',
    Grandson: 'Grandchild',
    Stepsister: 'Step Aunt/Uncle',
    Stepbrother: 'Step Aunt/Uncle',
    Stepmother: 'Step Parent',
    Stepfather: 'Step Parent',
    Stepdaughter: 'Step Sibling',
    Stepson: 'Step Sibling',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Daughter: {
    Self: 'Parent',
    Mother: 'Grandparent',
    Father: 'Grandparent',
    Son: 'Sibling',
    Sister: 'Aunt/Uncle',
    Brother: 'Aunt/Uncle',
    Aunt: 'Great Aunt/Uncle',
    Uncle: 'Great Aunt/Uncle',
    Niece: 'Cousin',
    Nephew: 'Cousin',
    'Cousin (female)': 'Second Cousin',
    'Cousin (male)': 'Second Cousin',
    Grandmother: 'Great Great Grandparent',
    Grandfather: 'Great Great Grandparent',
    Granddaughter: 'Niece/Nephew',
    Grandson: 'Niece/Nephew',
    Stepsister: 'Step Aunt/Uncle',
    Stepbrother: 'Step Aunt/Uncle',
    Stepmother: 'Step Grandparent',
    Stepfather: 'Step Grandparent',
    Stepdaughter: 'Step Sibling',
    Stepson: 'Step Sibling',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Son: {
    Self: 'Parent',
    Mother: 'Grandparent',
    Father: 'Grandparent',
    Daughter: 'Sibling',
    Sister: 'Aunt/Uncle',
    Brother: 'Aunt/Uncle',
    Aunt: 'Great Aunt/Uncle',
    Uncle: 'Great Aunt/Uncle',
    Niece: 'Cousin',
    Nephew: 'Cousin',
    'Cousin (female)': 'Second Cousin',
    'Cousin (male)': 'Second Cousin',
    Grandmother: 'Great Great Grandparent',
    Grandfather: 'Great Great Grandparent',
    Granddaughter: 'Niece/Nephew',
    Grandson: 'Niece/Nephew',
    Stepsister: 'Step Aunt/Uncle',
    Stepbrother: 'Step Aunt/Uncle',
    Stepmother: 'Step Grandparent',
    Stepfather: 'Step Grandparent',
    Stepdaughter: 'Step Sibling',
    Stepson: 'Step Sibling',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Sister: {
    Self: 'Sibling',
    Mother: 'Parent',
    Father: 'Parent',
    Daughter: 'Niece/Nephew',
    Son: 'Niece/Nephew',
    Brother: 'Sibling',
    Aunt: 'Aunt/Uncle',
    Uncle: 'Aunt/Uncle',
    Niece: 'Cousin',
    Nephew: 'Cousin',
    'Cousin (female)': 'Second Cousin',
    'Cousin (male)': 'Second Cousin',
    Grandmother: 'Grandparent',
    Grandfather: 'Grandparent',
    Granddaughter: 'Great Niece/Nephew',
    Grandson: 'Great Niece/Nephew',
    Stepsister: 'Step Sibling',
    Stepbrother: 'Step Sibling',
    Stepmother: 'Step Parent',
    Stepfather: 'Step Parent',
    Stepdaughter: 'Step Niece/Nephew',
    Stepson: 'Step Niece/Nephew',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Brother: {
    Self: 'Sibling',
    Mother: 'Parent',
    Father: 'Parent',
    Daughter: 'Niece/Nephew',
    Son: 'Niece/Nephew',
    Sister: 'Sibling',
    Aunt: 'Aunt/Uncle',
    Uncle: 'Aunt/Uncle',
    Niece: 'Cousin',
    Nephew: 'Cousin',
    'Cousin (female)': 'Second Cousin',
    'Cousin (male)': 'Second Cousin',
    Grandmother: 'Grandparent',
    Grandfather: 'Grandparent',
    Granddaughter: 'Great Niece/Nephew',
    Grandson: 'Great Niece/Nephew',
    Stepsister: 'Step Sibling',
    Stepbrother: 'Step Sibling',
    Stepmother: 'Step Parent',
    Stepfather: 'Step Parent',
    Stepdaughter: 'Step Niece/Nephew',
    Stepson: 'Step Niece/Nephew',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Aunt: {
    Self: 'Niece/Nephew',
    Mother: 'Grandparent',
    Father: 'Grandparent',
    Daughter: 'Cousin',
    Son: 'Cousin',
    Sister: 'Parent',
    Brother: 'Parent',
    Uncle: 'Aunt/Uncle',
    Niece: 'Sibling',
    Nephew: 'Sibling',
    'Cousin (female)': 'Cousin',
    'Cousin (male)': 'Cousin',
    Grandmother: 'Great Grandparent',
    Grandfather: 'Great Grandparent',
    Granddaughter: 'Second Cousin',
    Grandson: 'Second Cousin',
    Stepsister: 'Step Parent',
    Stepbrother: 'Step Parent',
    Stepmother: 'Step Grandparent',
    Stepfather: 'Step Grandparent',
    Stepdaughter: 'Step Cousin',
    Stepson: 'Step Cousin',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Uncle: {
    Self: 'Niece/Nephew',
    Mother: 'Grandparent',
    Father: 'Grandparent',
    Daughter: 'Cousin',
    Son: 'Cousin',
    Sister: 'Parent',
    Brother: 'Parent',
    Aunt: 'Aunt/Uncle',
    Niece: 'Sibling',
    Nephew: 'Sibling',
    'Cousin (female)': 'Cousin',
    'Cousin (male)': 'Cousin',
    Grandmother: 'Great Grandparent',
    Grandfather: 'Great Grandparent',
    Granddaughter: 'Second Cousin',
    Grandson: 'Second Cousin',
    Stepsister: 'Step Parent',
    Stepbrother: 'Step Parent',
    Stepmother: 'Step Grandparent',
    Stepfather: 'Step Grandparent',
    Stepdaughter: 'Step Cousin',
    Stepson: 'Step Cousin',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Niece: {
    Self: 'Aunt/Uncle',
    Mother: 'Great Grandparent',
    Father: 'Great Grandparent',
    Daughter: 'Second Cousin',
    Son: 'Second Cousin',
    Sister: 'Cousin',
    Brother: 'Cousin',
    Aunt: 'Sibling',
    Uncle: 'Sibling',
    Nephew: 'Sibling',
    'Cousin (female)': 'Parent',
    'Cousin (male)': 'Parent',
    Grandmother: 'Great Great Grandparent',
    Grandfather: 'Great Great Grandparent',
    Granddaughter: 'Third Cousin',
    Grandson: 'Third Cousin',
    Stepsister: 'Step Cousin',
    Stepbrother: 'Step Cousin',
    Stepmother: 'Step Great Grandparent',
    Stepfather: 'Step Great Grandparent',
    Stepdaughter: 'Step Second Cousin',
    Stepson: 'Step Second Cousin',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Nephew: {
    Self: 'Aunt/Uncle',
    Mother: 'Great Grandparent',
    Father: 'Great Grandparent',
    Daughter: 'Second Cousin',
    Son: 'Second Cousin',
    Sister: 'Cousin',
    Brother: 'Cousin',
    Aunt: 'Sibling',
    Uncle: 'Sibling',
    Niece: 'Sibling',
    'Cousin (female)': 'Parent',
    'Cousin (male)': 'Parent',
    Grandmother: 'Great Great Grandparent',
    Grandfather: 'Great Great Grandparent',
    Granddaughter: 'Third Cousin',
    Grandson: 'Third Cousin',
    Stepsister: 'Step Cousin',
    Stepbrother: 'Step Cousin',
    Stepmother: 'Step Great Grandparent',
    Stepfather: 'Step Great Grandparent',
    Stepdaughter: 'Step Second Cousin',
    Stepson: 'Step Second Cousin',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  'Cousin (female)': {
    Self: 'Cousin',
    Mother: 'Aunt/Uncle',
    Father: 'Aunt/Uncle',
    Daughter: 'Second Cousin',
    Son: 'Second Cousin',
    Sister: 'Second Cousin',
    Brother: 'Second Cousin',
    Aunt: 'Cousin',
    Uncle: 'Cousin',
    Niece: 'Parent',
    Nephew: 'Parent',
    'Cousin (male)': 'Sibling',
    Grandmother: 'Great Aunt/Uncle',
    Grandfather: 'Great Aunt/Uncle',
    Granddaughter: 'Third Cousin',
    Grandson: 'Third Cousin',
    Stepsister: 'Step Second Cousin',
    Stepbrother: 'Step Second Cousin',
    Stepmother: 'Step Aunt/Uncle',
    Stepfather: 'Step Aunt/Uncle',
    Stepdaughter: 'Step Second Cousin',
    Stepson: 'Step Second Cousin',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  'Cousin (male)': {
    Self: 'Cousin',
    Mother: 'Aunt/Uncle',
    Father: 'Aunt/Uncle',
    Daughter: 'Second Cousin',
    Son: 'Second Cousin',
    Sister: 'Second Cousin',
    Brother: 'Second Cousin',
    Aunt: 'Cousin',
    Uncle: 'Cousin',
    Niece: 'Parent',
    Nephew: 'Parent',
    'Cousin (female)': 'Sibling',
    Grandmother: 'Great Aunt/Uncle',
    Grandfather: 'Great Aunt/Uncle',
    Granddaughter: 'Third Cousin',
    Grandson: 'Third Cousin',
    Stepsister: 'Step Second Cousin',
    Stepbrother: 'Step Second Cousin',
    Stepmother: 'Step Aunt/Uncle',
    Stepfather: 'Step Aunt/Uncle',
    Stepdaughter: 'Step Second Cousin',
    Stepson: 'Step Second Cousin',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Grandmother: {
    Self: 'Grandchild',
    Mother: 'Child',
    Father: 'Child',
    Daughter: 'Great Grandchild',
    Son: 'Great Grandchild',
    Sister: 'Grandchild',
    Brother: 'Grandchild',
    Aunt: 'Child',
    Uncle: 'Child',
    Niece: 'Grandchild',
    Nephew: 'Grandchild',
    'Cousin (female)': 'Grandchild',
    'Cousin (male)': 'Grandchild',
    Grandfather: 'Partner/Spouse',
    Granddaughter: 'Great Great Grandchild',
    Grandson: 'Great Great Grandchild',
    Stepsister: 'Step Grandchild',
    Stepbrother: 'Step Grandchild',
    Stepmother: 'Family Member',
    Stepfather: 'Family Member',
    Stepdaughter: 'Step Great Grandchild',
    Stepson: 'Step Great Grandchild',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Grandfather: {
    Self: 'Grandchild',
    Mother: 'Child',
    Father: 'Child',
    Daughter: 'Great Grandchild',
    Son: 'Great Grandchild',
    Sister: 'Grandchild',
    Brother: 'Grandchild',
    Aunt: 'Child',
    Uncle: 'Child',
    Niece: 'Grandchild',
    Nephew: 'Grandchild',
    'Cousin (female)': 'Grandchild',
    'Cousin (male)': 'Grandchild',
    Grandmother: 'Partner/Spouse',
    Granddaughter: 'Great Great Grandchild',
    Grandson: 'Great Great Grandchild',
    Stepsister: 'Step Grandchild',
    Stepbrother: 'Step Grandchild',
    Stepmother: 'Family Member',
    Stepfather: 'Family Member',
    Stepdaughter: 'Step Great Grandchild',
    Stepson: 'Step Great Grandchild',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Granddaughter: {
    Self: 'Grandparent',
    Mother: 'Great Grandparent',
    Father: 'Great Grandparent',
    Daughter: 'Great Great Grandparent',
    Son: 'Great Great Grandparent',
    Sister: 'Great Aunt/Uncle',
    Brother: 'Great Aunt/Uncle',
    Aunt: 'Great Great Aunt/Uncle',
    Uncle: 'Great Great Aunt/Uncle',
    Niece: 'Third Cousin',
    Nephew: 'Third Cousin',
    'Cousin (female)': 'Third Cousin',
    'Cousin (male)': 'Third Cousin',
    Grandmother: 'Great Great Great Grandparent',
    Grandfather: 'Great Great Great Grandparent',
    Grandson: 'Sibling',
    Stepsister: 'Step Great Aunt/Uncle',
    Stepbrother: 'Step Great Aunt/Uncle',
    Stepmother: 'Step Great Grandparent',
    Stepfather: 'Step Great Grandparent',
    Stepdaughter: 'Step Sibling',
    Stepson: 'Step Sibling',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Grandson: {
    Self: 'Grandparent',
    Mother: 'Great Grandparent',
    Father: 'Great Grandparent',
    Daughter: 'Great Great Grandparent',
    Son: 'Great Great Grandparent',
    Sister: 'Great Aunt/Uncle',
    Brother: 'Great Aunt/Uncle',
    Aunt: 'Great Great Aunt/Uncle',
    Uncle: 'Great Great Aunt/Uncle',
    Niece: 'Third Cousin',
    Nephew: 'Third Cousin',
    'Cousin (female)': 'Third Cousin',
    'Cousin (male)': 'Third Cousin',
    Grandmother: 'Great Great Great Grandparent',
    Grandfather: 'Great Great Great Grandparent',
    Granddaughter: 'Sibling',
    Stepsister: 'Step Great Aunt/Uncle',
    Stepbrother: 'Step Great Aunt/Uncle',
    Stepmother: 'Step Great Grandparent',
    Stepfather: 'Step Great Grandparent',
    Stepdaughter: 'Step Sibling',
    Stepson: 'Step Sibling',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Stepsister: {
    Self: 'Step Sibling',
    Mother: 'Step Parent',
    Father: 'Step Parent',
    Daughter: 'Step Niece/Nephew',
    Son: 'Step Niece/Nephew',
    Sister: 'Step Sibling',
    Brother: 'Step Sibling',
    Aunt: 'Step Aunt/Uncle',
    Uncle: 'Step Aunt/Uncle',
    Niece: 'Step Cousin',
    Nephew: 'Step Cousin',
    'Cousin (female)': 'Step Second Cousin',
    'Cousin (male)': 'Step Second Cousin',
    Grandmother: 'Step Grandparent',
    Grandfather: 'Step Grandparent',
    Granddaughter: 'Step Great Niece/Nephew',
    Grandson: 'Step Great Niece/Nephew',
    Stepbrother: 'Step Sibling',
    Stepmother: 'Step Parent',
    Stepfather: 'Step Parent',
    Stepdaughter: 'Step Niece/Nephew',
    Stepson: 'Step Niece/Nephew',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Stepbrother: {
    Self: 'Step Sibling',
    Mother: 'Step Parent',
    Father: 'Step Parent',
    Daughter: 'Step Niece/Nephew',
    Son: 'Step Niece/Nephew',
    Sister: 'Step Sibling',
    Brother: 'Step Sibling',
    Aunt: 'Step Aunt/Uncle',
    Uncle: 'Step Aunt/Uncle',
    Niece: 'Step Cousin',
    Nephew: 'Step Cousin',
    'Cousin (female)': 'Step Second Cousin',
    'Cousin (male)': 'Step Second Cousin',
    Grandmother: 'Step Grandparent',
    Grandfather: 'Step Grandparent',
    Granddaughter: 'Step Great Niece/Nephew',
    Grandson: 'Step Great Niece/Nephew',
    Stepsister: 'Step Sibling',
    Stepmother: 'Step Parent',
    Stepfather: 'Step Parent',
    Stepdaughter: 'Step Niece/Nephew',
    Stepson: 'Step Niece/Nephew',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Stepmother: {
    Self: 'Step Child',
    Mother: 'Family Member',
    Father: 'Partner/Spouse',
    Daughter: 'Step Sibling',
    Son: 'Step Sibling',
    Sister: 'Step Aunt/Uncle',
    Brother: 'Step Aunt/Uncle',
    Aunt: 'Step Great Aunt/Uncle',
    Uncle: 'Step Great Aunt/Uncle',
    Niece: 'Step Cousin',
    Nephew: 'Step Cousin',
    'Cousin (female)': 'Step Second Cousin',
    'Cousin (male)': 'Step Second Cousin',
    Grandmother: 'Family Member',
    Grandfather: 'Family Member',
    Granddaughter: 'Step Grandchild',
    Grandson: 'Step Grandchild',
    Stepsister: 'Step Aunt/Uncle',
    Stepbrother: 'Step Aunt/Uncle',
    Stepfather: 'Family Member',
    Stepdaughter: 'Step Sibling',
    Stepson: 'Step Sibling',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Stepfather: {
    Self: 'Step Child',
    Mother: 'Partner/Spouse',
    Father: 'Family Member',
    Daughter: 'Step Sibling',
    Son: 'Step Sibling',
    Sister: 'Step Aunt/Uncle',
    Brother: 'Step Aunt/Uncle',
    Aunt: 'Step Great Aunt/Uncle',
    Uncle: 'Step Great Aunt/Uncle',
    Niece: 'Step Cousin',
    Nephew: 'Step Cousin',
    'Cousin (female)': 'Step Second Cousin',
    'Cousin (male)': 'Step Second Cousin',
    Grandmother: 'Family Member',
    Grandfather: 'Family Member',
    Granddaughter: 'Step Grandchild',
    Grandson: 'Step Grandchild',
    Stepsister: 'Step Aunt/Uncle',
    Stepbrother: 'Step Aunt/Uncle',
    Stepmother: 'Family Member',
    Stepdaughter: 'Step Sibling',
    Stepson: 'Step Sibling',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Stepdaughter: {
    Self: 'Step Parent',
    Mother: 'Step Grandparent',
    Father: 'Step Grandparent',
    Daughter: 'Step Sibling',
    Son: 'Step Sibling',
    Sister: 'Step Aunt/Uncle',
    Brother: 'Step Aunt/Uncle',
    Aunt: 'Step Great Aunt/Uncle',
    Uncle: 'Step Great Aunt/Uncle',
    Niece: 'Step Cousin',
    Nephew: 'Step Cousin',
    'Cousin (female)': 'Step Second Cousin',
    'Cousin (male)': 'Step Second Cousin',
    Grandmother: 'Step Great Grandparent',
    Grandfather: 'Step Great Grandparent',
    Granddaughter: 'Step Niece/Nephew',
    Grandson: 'Step Niece/Nephew',
    Stepsister: 'Step Aunt/Uncle',
    Stepbrother: 'Step Aunt/Uncle',
    Stepmother: 'Step Grandparent',
    Stepfather: 'Step Grandparent',
    Stepson: 'Step Sibling',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  Stepson: {
    Self: 'Step Parent',
    Mother: 'Step Grandparent',
    Father: 'Step Grandparent',
    Daughter: 'Step Sibling',
    Son: 'Step Sibling',
    Sister: 'Step Aunt/Uncle',
    Brother: 'Step Aunt/Uncle',
    Aunt: 'Step Great Aunt/Uncle',
    Uncle: 'Step Great Aunt/Uncle',
    Niece: 'Step Cousin',
    Nephew: 'Step Cousin',
    'Cousin (female)': 'Step Second Cousin',
    'Cousin (male)': 'Step Second Cousin',
    Grandmother: 'Step Great Grandparent',
    Grandfather: 'Step Great Grandparent',
    Granddaughter: 'Step Niece/Nephew',
    Grandson: 'Step Niece/Nephew',
    Stepsister: 'Step Aunt/Uncle',
    Stepbrother: 'Step Aunt/Uncle',
    Stepmother: 'Step Grandparent',
    Stepfather: 'Step Grandparent',
    Stepdaughter: 'Step Sibling',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  'Sister-in-law': {
    Self: 'In-law Relative',
    Mother: 'In-law Elder',
    Father: 'In-law Elder',
    Daughter: 'In-law Relative',
    Son: 'In-law Relative',
    Sister: 'In-law Relative',
    Brother: 'In-law Relative',
    Aunt: 'In-law Relative',
    Uncle: 'In-law Relative',
    Niece: 'In-law Relative',
    Nephew: 'In-law Relative',
    'Cousin (female)': 'In-law Relative',
    'Cousin (male)': 'In-law Relative',
    Grandmother: 'In-law Elder',
    Grandfather: 'In-law Elder',
    Granddaughter: 'In-law Relative',
    Grandson: 'In-law Relative',
    Stepsister: 'In-law Relative',
    Stepbrother: 'In-law Relative',
    Stepmother: 'In-law Relative',
    Stepfather: 'In-law Relative',
    Stepdaughter: 'In-law Relative',
    Stepson: 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  'Brother-in-law': {
    Self: 'In-law Relative',
    Mother: 'In-law Elder',
    Father: 'In-law Elder',
    Daughter: 'In-law Relative',
    Son: 'In-law Relative',
    Sister: 'In-law Relative',
    Brother: 'In-law Relative',
    Aunt: 'In-law Relative',
    Uncle: 'In-law Relative',
    Niece: 'In-law Relative',
    Nephew: 'In-law Relative',
    'Cousin (female)': 'In-law Relative',
    'Cousin (male)': 'In-law Relative',
    Grandmother: 'In-law Elder',
    Grandfather: 'In-law Elder',
    Granddaughter: 'In-law Relative',
    Grandson: 'In-law Relative',
    Stepsister: 'In-law Relative',
    Stepbrother: 'In-law Relative',
    Stepmother: 'In-law Relative',
    Stepfather: 'In-law Relative',
    Stepdaughter: 'In-law Relative',
    Stepson: 'In-law Relative',
    'Sister-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Elder',
    'Father-in-law': 'In-law Elder',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  'Mother-in-law': {
    Self: 'In-law Child',
    Mother: 'In-law Family',
    Father: 'In-law Family',
    Daughter: 'In-law Relative',
    Son: 'In-law Relative',
    Sister: 'In-law Relative',
    Brother: 'In-law Relative',
    Aunt: 'In-law Relative',
    Uncle: 'In-law Relative',
    Niece: 'In-law Relative',
    Nephew: 'In-law Relative',
    'Cousin (female)': 'In-law Relative',
    'Cousin (male)': 'In-law Relative',
    Grandmother: 'In-law Elder',
    Grandfather: 'In-law Elder',
    Granddaughter: 'In-law Relative',
    Grandson: 'In-law Relative',
    Stepsister: 'In-law Relative',
    Stepbrother: 'In-law Relative',
    Stepmother: 'In-law Relative',
    Stepfather: 'In-law Relative',
    Stepdaughter: 'In-law Relative',
    Stepson: 'In-law Relative',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Father-in-law': 'In-law Partner',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  'Father-in-law': {
    Self: 'In-law Child',
    Mother: 'In-law Family',
    Father: 'In-law Family',
    Daughter: 'In-law Relative',
    Son: 'In-law Relative',
    Sister: 'In-law Relative',
    Brother: 'In-law Relative',
    Aunt: 'In-law Relative',
    Uncle: 'In-law Relative',
    Niece: 'In-law Relative',
    Nephew: 'In-law Relative',
    'Cousin (female)': 'In-law Relative',
    'Cousin (male)': 'In-law Relative',
    Grandmother: 'In-law Elder',
    Grandfather: 'In-law Elder',
    Granddaughter: 'In-law Relative',
    Grandson: 'In-law Relative',
    Stepsister: 'In-law Relative',
    Stepbrother: 'In-law Relative',
    Stepmother: 'In-law Relative',
    Stepfather: 'In-law Relative',
    Stepdaughter: 'In-law Relative',
    Stepson: 'In-law Relative',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Partner',
    'Daughter-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  'Daughter-in-law': {
    Self: 'In-law Parent',
    Mother: 'In-law Grandparent',
    Father: 'In-law Grandparent',
    Daughter: 'In-law Relative',
    Son: 'In-law Spouse',
    Sister: 'In-law Relative',
    Brother: 'In-law Relative',
    Aunt: 'In-law Relative',
    Uncle: 'In-law Relative',
    Niece: 'In-law Relative',
    Nephew: 'In-law Relative',
    'Cousin (female)': 'In-law Relative',
    'Cousin (male)': 'In-law Relative',
    Grandmother: 'In-law Elder',
    Grandfather: 'In-law Elder',
    Granddaughter: 'In-law Relative',
    Grandson: 'In-law Relative',
    Stepsister: 'In-law Relative',
    Stepbrother: 'In-law Relative',
    Stepmother: 'In-law Relative',
    Stepfather: 'In-law Relative',
    Stepdaughter: 'In-law Relative',
    Stepson: 'In-law Relative',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Relative',
    'Father-in-law': 'In-law Relative',
    'Son-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  'Son-in-law': {
    Self: 'In-law Parent',
    Mother: 'In-law Grandparent',
    Father: 'In-law Grandparent',
    Daughter: 'In-law Spouse',
    Son: 'In-law Relative',
    Sister: 'In-law Relative',
    Brother: 'In-law Relative',
    Aunt: 'In-law Relative',
    Uncle: 'In-law Relative',
    Niece: 'In-law Relative',
    Nephew: 'In-law Relative',
    'Cousin (female)': 'In-law Relative',
    'Cousin (male)': 'In-law Relative',
    Grandmother: 'In-law Elder',
    Grandfather: 'In-law Elder',
    Granddaughter: 'In-law Relative',
    Grandson: 'In-law Relative',
    Stepsister: 'In-law Relative',
    Stepbrother: 'In-law Relative',
    Stepmother: 'In-law Relative',
    Stepfather: 'In-law Relative',
    Stepdaughter: 'In-law Relative',
    Stepson: 'In-law Relative',
    'Sister-in-law': 'In-law Relative',
    'Brother-in-law': 'In-law Relative',
    'Mother-in-law': 'In-law Relative',
    'Father-in-law': 'In-law Relative',
    'Daughter-in-law': 'In-law Relative',
    'Family Friend': 'Family Friend',
    Pet: 'Pet',
  },

  'Family Friend': {
    Self: 'Family Friend',
    Mother: 'Family Friend',
    Father: 'Family Friend',
    Daughter: 'Family Friend',
    Son: 'Family Friend',
    Sister: 'Family Friend',
    Brother: 'Family Friend',
    Aunt: 'Family Friend',
    Uncle: 'Family Friend',
    Niece: 'Family Friend',
    Nephew: 'Family Friend',
    'Cousin (female)': 'Family Friend',
    'Cousin (male)': 'Family Friend',
    Grandmother: 'Family Friend',
    Grandfather: 'Family Friend',
    Granddaughter: 'Family Friend',
    Grandson: 'Family Friend',
    Stepsister: 'Family Friend',
    Stepbrother: 'Family Friend',
    Stepmother: 'Family Friend',
    Stepfather: 'Family Friend',
    Stepdaughter: 'Family Friend',
    Stepson: 'Family Friend',
    'Sister-in-law': 'Family Friend',
    'Brother-in-law': 'Family Friend',
    'Mother-in-law': 'Family Friend',
    'Father-in-law': 'Family Friend',
    'Daughter-in-law': 'Family Friend',
    'Son-in-law': 'Family Friend',
    Pet: 'Family Friend',
  },

  Pet: {
    Self: 'Owner',
    Mother: 'Family Member',
    Father: 'Family Member',
    Daughter: 'Family Member',
    Son: 'Family Member',
    Sister: 'Family Member',
    Brother: 'Family Member',
    Aunt: 'Family Member',
    Uncle: 'Family Member',
    Niece: 'Family Member',
    Nephew: 'Family Member',
    'Cousin (female)': 'Family Member',
    'Cousin (male)': 'Family Member',
    Grandmother: 'Family Member',
    Grandfather: 'Family Member',
    Granddaughter: 'Family Member',
    Grandson: 'Family Member',
    Stepsister: 'Family Member',
    Stepbrother: 'Family Member',
    Stepmother: 'Family Member',
    Stepfather: 'Family Member',
    Stepdaughter: 'Family Member',
    Stepson: 'Family Member',
    'Sister-in-law': 'Family Member',
    'Brother-in-law': 'Family Member',
    'Mother-in-law': 'Family Member',
    'Father-in-law': 'Family Member',
    'Daughter-in-law': 'Family Member',
    'Son-in-law': 'Family Member',
    'Family Friend': 'Family Friend',
    Pet: 'Pet Sibling',
  },
};

const MARITAL_STATUS = [
  { label: 'Not married', value: 'Not married' },
  { label: 'Engaged', value: 'Engaged' },
  { label: 'Married', value: 'Married' },
  { label: 'Domestic partnership', value: 'Domestic partnership' },
  { label: 'In Civil Union', value: 'In Civil Union' },
  { label: 'Separated', value: 'Separated' },
  { label: 'Divorced', value: 'Divorced' },
  { label: 'Widowed', value: 'Widowed' },
];

const POLITICAL_EXPOSURE = [
  { label: 'Yes', value: true },
  { label: 'No', value: false },
];

// const RESIDENCE_STATUS = [
//   'Resident',
//   'Non resident Indian',
//   'Overseas Citizen of India',
//   'Foreign National',
// ];

const RISK_PROFILE = [
  { label: 'Low', value: 'Low' },
  { label: 'Medium', value: 'Medium' },
  { label: 'High', value: 'High' },
];

const CONTACT_STATUS = [
  { label: 'Attempted to contact', value: 'Attempted to contact' },
  { label: 'Negotiation', value: 'Negotiation' },
  { label: 'Closed Won', value: 'Closed Won' },
  { label: 'Closed Lost', value: 'Closed Lost' },
  { label: 'Unqualified', value: 'Unqualified' },
  { label: 'Qualified', value: 'Qualified' },
];

const INDUSTRY = [
  { label: 'Accounting', value: 'Accounting' },
  { label: 'Agriculture', value: 'Agriculture' },
  { label: 'Airlines/Aviation', value: 'Airlines/Aviation' },
  { label: 'Alternative Dispute Resolution', value: 'Alternative Dispute Resolution' },
  { label: 'Alternative Medicine', value: 'Alternative Medicine' },
  { label: 'Animation', value: 'Animation' },
  { label: 'Apparel/Fashion', value: 'Apparel/Fashion' },
  { label: 'Architecture/Planning', value: 'Architecture/Planning' },
  { label: 'Arts/Crafts', value: 'Arts/Crafts' },
  { label: 'Automotive', value: 'Automotive' },
  { label: 'Aviation/Aerospace', value: 'Aviation/Aerospace' },
  { label: 'Banking/Mortgage', value: 'Banking/Mortgage' },
  { label: 'Biotechnology/Greentech', value: 'Biotechnology/Greentech' },
  { label: 'Broadcast Media', value: 'Broadcast Media' },
  { label: 'Building Materials', value: 'Building Materials' },
  { label: 'Business Supplies/Equipment', value: 'Business Supplies/Equipment' },
  { label: 'Capital Markets/Hedge Fund/Private Equity', value: 'Capital Markets/Hedge Fund/Private Equity' },
  { label: 'Chemicals', value: 'Chemicals' },
  { label: 'Civic/Social Organization', value: 'Civic/Social Organization' },
  { label: 'Civil Engineering', value: 'Civil Engineering' },
  { label: 'Commercial Real Estate', value: 'Commercial Real Estate' },
  { label: 'Computer Games', value: 'Computer Games' },
  { label: 'Computer Hardware', value: 'Computer Hardware' },
  { label: 'Computer Networking', value: 'Computer Networking' },
  { label: 'Computer Software/Engineering', value: 'Computer Software/Engineering' },
  { label: 'Computer/Network Security', value: 'Computer/Network Security' },
  { label: 'Construction', value: 'Construction' },
  { label: 'Consumer Electronics', value: 'Consumer Electronics' },
  { label: 'Consumer Goods', value: 'Consumer Goods' },
  { label: 'Consumer Services', value: 'Consumer Services' },
  { label: 'Cosmetics', value: 'Cosmetics' },
  { label: 'Dairy', value: 'Dairy' },
  { label: 'Defense/Space', value: 'Defense/Space' },
  { label: 'Design', value: 'Design' },
  { label: 'E-Learning', value: 'E-Learning' },
  { label: 'Education Management', value: 'Education Management' },
  { label: 'Electrical/Electronic Manufacturing', value: 'Electrical/Electronic Manufacturing' },
  { label: 'Entertainment/Movie Production', value: 'Entertainment/Movie Production' },
  { label: 'Environmental Services', value: 'Environmental Services' },
  { label: 'Events Services', value: 'Events Services' },
  { label: 'Executive Office', value: 'Executive Office' },
  { label: 'Facilities Services', value: 'Facilities Services' },
  { label: 'Farming', value: 'Farming' },
  { label: 'Financial Services', value: 'Financial Services' },
  { label: 'Fine Art', value: 'Fine Art' },
  { label: 'Fishery', value: 'Fishery' },
  { label: 'Food Production', value: 'Food Production' },
  { label: 'Food/Beverages', value: 'Food/Beverages' },
  { label: 'Fundraising', value: 'Fundraising' },
  { label: 'Furniture', value: 'Furniture' },
  { label: 'Gambling/Casinos', value: 'Gambling/Casinos' },
  { label: 'Glass/Ceramics/Concrete', value: 'Glass/Ceramics/Concrete' },
  { label: 'Government Administration', value: 'Government Administration' },
  { label: 'Government Relations', value: 'Government Relations' },
  { label: 'Graphic Design/Web Design', value: 'Graphic Design/Web Design' },
  { label: 'Health/Fitness', value: 'Health/Fitness' },
  { label: 'Higher Education/Academia', value: 'Higher Education/Academia' },
  { label: 'Hospital/Health Care', value: 'Hospital/Health Care' },
  { label: 'Hospitality', value: 'Hospitality' },
  { label: 'Human Resources/HR', value: 'Human Resources/HR' },
  { label: 'Import/Export', value: 'Import/Export' },
  { label: 'Individual/Family Services', value: 'Individual/Family Services' },
  { label: 'Industrial Automation', value: 'Industrial Automation' },
  { label: 'Information Services', value: 'Information Services' },
  { label: 'Information Technology/IT', value: 'Information Technology/IT' },
  { label: 'Insurance', value: 'Insurance' },
  { label: 'International Affairs', value: 'International Affairs' },
  { label: 'International Trade/Development', value: 'International Trade/Development' },
  { label: 'Internet', value: 'Internet' },
  { label: 'Investment Banking/Venture', value: 'Investment Banking/Venture' },
  { label: 'Investment Management/Hedge Fund/Private Equity', value: 'Investment Management/Hedge Fund/Private Equity' },
  { label: 'Judiciary', value: 'Judiciary' },
  { label: 'Law Enforcement', value: 'Law Enforcement' },
  { label: 'Law Practice/Law Firms', value: 'Law Practice/Law Firms' },
  { label: 'Legal Services', value: 'Legal Services' },
  { label: 'Legislative Office', value: 'Legislative Office' },
  { label: 'Leisure/Travel', value: 'Leisure/Travel' },
  { label: 'Library', value: 'Library' },
  { label: 'Logistics/Procurement', value: 'Logistics/Procurement' },
  { label: 'Luxury Goods/Jewelry', value: 'Luxury Goods/Jewelry' },
  { label: 'Machinery', value: 'Machinery' },
  { label: 'Management Consulting', value: 'Management Consulting' },
  { label: 'Maritime', value: 'Maritime' },
  { label: 'Market Research', value: 'Market Research' },
  { label: 'Marketing/Advertising/Sales', value: 'Marketing/Advertising/Sales' },
  { label: 'Mechanical or Industrial Engineering', value: 'Mechanical or Industrial Engineering' },
  { label: 'Media Production', value: 'Media Production' },
  { label: 'Medical Equipment', value: 'Medical Equipment' },
  { label: 'Medical Practice', value: 'Medical Practice' },
  { label: 'Mental Health Care', value: 'Mental Health Care' },
  { label: 'Military Industry', value: 'Military Industry' },
  { label: 'Mining/Metals', value: 'Mining/Metals' },
  { label: 'Motion Pictures/Film', value: 'Motion Pictures/Film' },
  { label: 'Museums/Institutions', value: 'Museums/Institutions' },
  { label: 'Music', value: 'Music' },
  { label: 'Nanotechnology', value: 'Nanotechnology' },
  { label: 'Newspapers/Journalism', value: 'Newspapers/Journalism' },
  { label: 'Non-Profit/Volunteering', value: 'Non-Profit/Volunteering' },
  { label: 'Oil/Energy/Solar/Greentech', value: 'Oil/Energy/Solar/Greentech' },
  { label: 'Online Publishing', value: 'Online Publishing' },
  { label: 'Other Industry', value: 'Other Industry' },
  { label: 'Outsourcing/Offshoring', value: 'Outsourcing/Offshoring' },
  { label: 'Package/Freight Delivery', value: 'Package/Freight Delivery' },
  { label: 'Packaging/Containers', value: 'Packaging/Containers' },
  { label: 'Paper/Forest Products', value: 'Paper/Forest Products' },
  { label: 'Performing Arts', value: 'Performing Arts' },
  { label: 'Pharmaceuticals', value: 'Pharmaceuticals' },
  { label: 'Philanthropy', value: 'Philanthropy' },
  { label: 'Photography', value: 'Photography' },
  { label: 'Plastics', value: 'Plastics' },
  { label: 'Political Organization', value: 'Political Organization' },
  { label: 'Primary/Secondary Education', value: 'Primary/Secondary Education' },
  { label: 'Printing', value: 'Printing' },
  { label: 'Professional Training', value: 'Professional Training' },
  { label: 'Program Development', value: 'Program Development' },
  { label: 'Public Relations/PR', value: 'Public Relations/PR' },
  { label: 'Public Safety', value: 'Public Safety' },
  { label: 'Publishing Industry', value: 'Publishing Industry' },
  { label: 'Railroad Manufacture', value: 'Railroad Manufacture' },
  { label: 'Ranching', value: 'Ranching' },
  { label: 'Real Estate/Mortgage', value: 'Real Estate/Mortgage' },
  { label: 'Recreational Facilities/Services', value: 'Recreational Facilities/Services' },
  { label: 'Religious Institutions', value: 'Religious Institutions' },
  { label: 'Renewables/Environment', value: 'Renewables/Environment' },
  { label: 'Research Industry', value: 'Research Industry' },
  { label: 'Restaurants', value: 'Restaurants' },
  { label: 'Retail Industry', value: 'Retail Industry' },
  { label: 'Security/Investigations', value: 'Security/Investigations' },
  { label: 'Semiconductors', value: 'Semiconductors' },
  { label: 'Shipbuilding', value: 'Shipbuilding' },
  { label: 'Sporting Goods', value: 'Sporting Goods' },
  { label: 'Sports', value: 'Sports' },
  { label: 'Staffing/Recruiting', value: 'Staffing/Recruiting' },
  { label: 'Supermarkets', value: 'Supermarkets' },
  { label: 'Telecommunications', value: 'Telecommunications' },
  { label: 'Textiles', value: 'Textiles' },
  { label: 'Think Tanks', value: 'Think Tanks' },
  { label: 'Tobacco', value: 'Tobacco' },
  { label: 'Translation/Localization', value: 'Translation/Localization' },
  { label: 'Transportation', value: 'Transportation' },
  { label: 'Utilities', value: 'Utilities' },
  { label: 'Venture Capital/VC', value: 'Venture Capital/VC' },
  { label: 'Veterinary', value: 'Veterinary' },
  { label: 'Warehousing', value: 'Warehousing' },
  { label: 'Wholesale', value: 'Wholesale' },
  { label: 'Wine/Spirits', value: 'Wine/Spirits' },
  { label: 'Wireless', value: 'Wireless' },
  { label: 'Writing/Editing', value: 'Writing/Editing' },
];

const CONTACT_SOURCE = [
  { label: 'Organic Search', value: 'Organic Search' },
  { label: 'Paid Search', value: 'Paid Search' },
  { label: 'Email marketing', value: 'Email marketing' },
  { label: 'Organic Social', value: 'Organic Social' },
  { label: 'Referrals', value: 'Referrals' },
  { label: 'Direct Traffic', value: 'Direct Traffic' },
  { label: 'Offline word of mouth', value: 'Offline word of mouth' },
  { label: 'Other offline sources', value: 'Other offline sources' },
  { label: 'Paid Social', value: 'Paid Social' },
];

const CONTACT_DEFAULT_COUNTRY = [{ label: 'India', value: 'India' }];

const CALL_OUTCOME = [
  { label: 'No answer', value: 'No answer' },
  { label: 'Busy', value: 'Busy' },
  { label: 'Wrong number', value: 'Wrong number' },
  { label: 'Left live message', value: 'Left live message' },
  { label: 'Left voicemail', value: 'Left voicemail' },
  { label: 'Connected', value: 'Connected' },
  { label: 'Demo scheduled', value: 'Demo scheduled' },
  { label: 'Meeting scheduled', value: 'Meeting scheduled' },
  { label: 'Follow-up required', value: 'Follow-up required' },
  { label: 'Not interested', value: 'Not interested' },
  { label: 'Bad timing', value: 'Bad timing' },
];

module.exports = {
  ROLES,
  CONTACT_FILTERS,
  IS_GROUP_HEAD,
  RELATIONSHIP_GROUP_HEAD,
  RELATIONSHIP_MATRIX,
  MARITAL_STATUS,
  POLITICAL_EXPOSURE,
  RISK_PROFILE,
  CONTACT_STATUS,
  INDUSTRY,
  CONTACT_SOURCE,
  CONTACT_DEFAULT_COUNTRY,
  CALL_OUTCOME,
};
